### ISSUE TITLE
Add ability to set Capabilities to Privileged Container Experiment

### ISSUE THREAD

**Issue by glenn-operant** [OperantAI/secops-chaos#40]
In our Privileged Container experiment, which should add the functionality to allow the setting of [Capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html). 

This is another method of running a container with privileged permissions, in Kubernetes objects it gets added under the Security Context.

```yaml
  securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
```
