### ISSUE TITLE
Allow running own image in Privileged Container Experiment

### ISSUE THREAD

**Issue by glenn-operant** [OperantAI/secops-chaos#76]
```yaml
experiments:
  - metadata:
      name: run-privileged-container
      type: privileged_container
      namespace: default
    parameters:
      image: "my-image"
      privileged: true
      host_pid: true
      host_network: true
      run_as_root: true
```
